export interface Pokemon {
  id?: number; // Optional because it's auto-generated by IndexedDB
  name: string;
  prompt: string;
  imageUrl: string;
  createdAt: Date;
  rarity: string;
}

export interface TokenBalance {
  id: 'tokenBalance';
  amount: number;
}

// FIX: Add missing type definitions for PokemonApiService.
export enum PokemonStatus {
  OWNED = 'OWNED',
}

// FIX: Add missing type definitions for PokemonApiService.
export enum PokemonRarity {
  COMMON = 'COMMON',
  UNCOMMON = 'UNCOMMON',
  RARE = 'RARE',
  EPIC = 'EPIC',
  LEGENDARY = 'LEGENDARY',
}

// FIX: Add missing type definitions for PokemonApiService.
export interface ApiErrorResponse {
  error: {
    code: string;
    message: string;
    timestamp: string;
  };
}